mp.openapi.extensions.smallrye.info.title=Book Microservice
mp.openapi.extensions.smallrye.info.version=1.0
mp.openapi.extensions.smallrye.info.description=Book Microservice API documentation
mp.openapi.extensions.smallrye.info.contact.name=Quarkus
mp.openapi.extensions.smallrye.info.contact.url=https://quarkus.io/

quarkus.http.cors.methods=GET,POST,PUT,DELETE
quarkus.http.cors.origins=*
quarkus.http.port=8667

#Primary Datasource
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=root
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/adventure_works
quarkus.datasource.jdbc.acquisition-timeout=5s
quarkus.datasource.jdbc.max-size=10
quarkus.datasource.jdbc.initial-size=5
quarkus.datasource.jdbc.min-size=5
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.database.default-schema=adventure_works
quarkus.hibernate-orm.packages=org.rest.resource.ms.entity

#Secondary Datasource
quarkus.datasource.std.db-kind=postgresql
quarkus.datasource.std.username=admin
quarkus.datasource.std.password=changeit
quarkus.datasource.std.jdbc.url=jdbc:postgresql://localhost:5432/public
quarkus.datasource.std.jdbc.acquisition-timeout=5s
quarkus.datasource.std.jdbc.max-size=6
quarkus.datasource.std.jdbc.initial-size=3
quarkus.datasource.std.jdbc.min-size=3
quarkus.hibernate-orm.std.datasource=std
quarkus.hibernate-orm.std.active=true
quarkus.hibernate-orm.std.database.generation=update
quarkus.hibernate-orm.std.database.default-schema=public
quarkus.hibernate-orm.std.packages=org.rest.resource.ms.pojo


quarkus.banner.enabled=false
quarkus.rest-client.number-ms.uri=http://localhost:7667
quarkus.smallrye-graphql-client.greet-ms.url=http://localhost:6070/graphql