---
#common configurations
mp:
  openapi:
    extensions:
      smallrye:
        info:
          title: "Book Microservice"
          version: "1.0"
          description: "Book Microservice API documentation"
          contact:
            name: "Quarkus"
            url: "https://quarkus.io/"
quarkus:
  http:
    cors:
      methods: GET,POST,PUT,DELETE
      origins: "*"

#dev configurations
"%dev":
  quarkus:
    http:
      port: 8667
# Primary Datasource
    datasource:
      db-kind: mysql
      username: root
      password: root
      jdbc:
        url: jdbc:mysql://localhost:3306/adventure_works
        acquisition-timeout: 5s
        max-size: 10
        initial-size: 5
        min-size: 5
# Secondary Datasource
    datasource2:
        db-kind: postgresql
        username: admin
        password: changeit
        jdbc:
          url: jdbc:postgresql://localhost:5423/postgres
          acquisition-timeout: 5s
          max-size: 6
          initial-size: 3
          min-size: 3
    hibernate-orm:
      database:
        generation: update
        default-schema: adventure_works
    hibername-orm2:
        datasource: postgres
        database:
          generation: update
          default-schema: postgres
        packages: org.rest.resource.ms.entity.Student
    banner:
      enabled: true
    rest-client:
        number-ms:
           uri: "http://localhost:7667"
    smallrye-graphql-client:
      greet-ms:
         url: "http://localhost:6070/graphql"

#prod configurations
"%prod":
  quarkus:
    http:
      port: 8669
    banner:
      enabled: true
    datasource:
      db-kind: mysql
      username: root
      password: root
      jdbc:
        url: jdbc:mysql://localhost:3306/adventure_works #changeit
    hibernate-orm:
      database:
        default-schema: adventure_works
        generation: update
    rest-client:
      number-ms:
        uri: "http://localhost:7667"
    smallrye-graphql-client:
      greet-ms:
        url: "http://localhost:6070/graphql"